blog/urls.py
from django.urls import path

from . import views
from blog.feeds import AllPostsRssFeed

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('search/', views.search, name='search'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    path('all/rss/', AllPostsRssFeed(), name='rss'),
]

blog/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
import markdown
from django.utils.html import strip_tags
import re
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.utils.functional import cached_property

class Category(models.Model):
    """
    django 要求模型必须继承 models.Model 类。
    Category 只需要一个简单的分类名 name 就可以了。
    CharField 指定了分类名 name 的数据类型，CharField 是字符型，
    CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
    当然 django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
    django 内置的全部类型可查看文档：
    https://docs.djangoproject.com/en/2.2/ref/models/fields/#field-types
    """

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    title = models.CharField('标题', max_length=70)
    body = models.TextField('正文')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    modified_time = models.DateTimeField('修改时间')
    excerpt = models.CharField('摘要', max_length=200, blank=True)
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0, editable=False)


    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

        # 先将 Markdown 文本渲染成 HTML 文本
        # strip_tags 去掉 HTML 文本的全部 HTML 标签
        # 从文本摘取前 54 个字符赋给 excerpt

        if not self.excerpt :
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})
    
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    
    @property
    def toc(self):
        return self.rich_content.get("toc", "")

    @property
    def body_html(self):
        return self.rich_content.get("content", "")

    @cached_property
    def rich_content(self):
        return generate_rich_content(self.body)

def generate_rich_content(value):
    md = markdown.Markdown(
        extensions=[
            "markdown.extensions.extra",
            "markdown.extensions.codehilite",
            # 记得在顶部引入 TocExtension 和 slugify
            TocExtension(slugify=slugify),
        ]
    )
    content = md.convert(value)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    toc = m.group(1) if m is not None else ""
    return {"content": content, "toc": toc}

comments/models.py
# Create your models here.
from django.db import models
from django.utils import timezone


class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址', blank=True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

blog/views.py
from django.shortcuts import render, get_object_or_404
import markdown
import re
from collections.abc import Iterable

from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.contrib import messages
from django.shortcuts import redirect
from django.db.models import Q
# Create your views here.

from django.http import HttpResponse
from .models import Post, Category, Tag
from django.views.generic import ListView
from pure_pagination.mixins import PaginationMixin

class IndexView(PaginationMixin, ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 10


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        # 记得在顶部引入 TocExtension 和 slugify
        TocExtension(slugify=slugify),
    ])
    post.body = md.convert(post.body)
    post.increase_views()

    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''

    return render(request, 'blog/detail.html', context={'post': post})


class ArchiveView(IndexView):
    def get_queryset(self):
        return super(ArchiveView, self).get_queryset().filter(created_time__year=self.kwargs.get('year'),
                                                              created_time__month=self.kwargs.get('month'))

class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 5

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

class TagView(IndexView):
    def get_queryset(self):
        t = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=t)
    
def tag(request, pk):
    # 记得在开始部分导入 Tag 类
    t = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=t).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


def search(request):
    q = request.GET.get('q')

    if not q:
        error_msg = "请输入搜索关键词"
        messages.add_message(request, messages.ERROR, error_msg, extra_tags='danger')
        return redirect('blog:index')

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'post_list': post_list})

templates/blog/base.html
{% load static %} {% load blog_extras %} {% load comments_extras %}
<!DOCTYPE html>
<html>
  <head>
    <title>Black &amp; White</title>
    <link
      href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css"
      rel="stylesheet"
    />
    <style>
      .codehilite {
        padding: 0;
      }

      /* for block of numbers */
      .hljs-ln-numbers {
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;

        text-align: center;
        color: #ccc;
        border-right: 1px solid #ccc;
        vertical-align: top;
        padding-right: 5px;
      }

      /* 搜索关键词高亮 */
      span.highlighted {
          color: red;
        }

      .hljs-ln-n {
        width: 30px;
      }

      /* for block of code */
      .hljs-ln .hljs-ln-code {
        padding-left: 10px;
        white-space: pre;
      }
    </style>

    <!-- meta -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}" />
    <link
      rel="stylesheet"
      href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
    />
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}" />
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}" />

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
  </head>

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  <body>
    <div class="container">
      <header id="site-header">
        <div class="row">
          <div class="col-md-4 col-sm-5 col-xs-8">
            <div class="logo">
              <h1>
                <a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a>
              </h1>
            </div>
          </div>
          <!-- col-md-4 -->
          <div class="col-md-8 col-sm-7 col-xs-4">
            <nav class="main-nav" role="navigation">
              <div class="navbar-header">
                <button
                  type="button"
                  id="trigger-overlay"
                  class="navbar-toggle"
                >
                  <span class="ion-navicon"></span>
                </button>
              </div>

              <div
                class="collapse navbar-collapse"
                id="bs-example-navbar-collapse-1"
              >
                <ul class="nav navbar-nav navbar-right">
                  <li class="cl-effect-11">
                    <a href="{% url 'blog:index' %}" data-hover="首页">首页</a>
                  </li>
                  <li class="cl-effect-11">
                    <a href="full-width.html" data-hover="博客">博客</a>
                  </li>
                  <li class="cl-effect-11">
                    <a href="about.html" data-hover="关于">关于</a>
                  </li>
                  <li class="cl-effect-11">
                    <a href="contact.html" data-hover="联系">联系</a>
                  </li>
                </ul>
              </div>
              <!-- /.navbar-collapse -->
            </nav>
            <div id="header-search-box">
              <a id="search-menu" href="#"
                ><span id="search-icon" class="ion-ios-search-strong"></span
              ></a>
              <div id="search-form" class="search-form">
                <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                  <input type="search" name="q" placeholder="搜索" required>
                  <button type="submit"><span class="ion-ios-search-strong"></span></button>
                </form>              
              </div>
            </div>
          </div>
          <!-- col-md-8 -->
        </div>
      </header>
    </div>
    <div class="copyrights">
      Collect from <a href="http://www.cssmoban.com/">网页模板</a>
    </div>
    <div class="copyrights">
      Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a>
    </div>

    <div class="content-body">
      <div class="container">
        <div class="row">
          <main class="col-md-8">{% block main %} {% endblock main %}</main>
          <aside class="col-md-4">
            {% block toc %} {% endblock toc %} {% show_recent_posts %}
            {%show_archives %} {% show_categories %} {% show_tags %}
            <div class="rss">
              <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
          </div>          
          </aside>
        </div>
      </div>
    </div>
    <footer id="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p class="copyright">
              &copy 2017 - 采集自<a
                href="http://www.cssmoban.com/"
                target="_blank"
                title="模板之家"
                >模板之家</a
              >
              - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank"
                >追梦人物的博客</a
              >修改
            </p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
      <button type="button" class="overlay-close">
        <span class="ion-ios-close-empty"></span>
      </button>
      <nav>
        <ul>
          <li><a href="index.html">首页</a></li>
          <li><a href="full-width.html">博客</a></li>
          <li><a href="about.html">关于</a></li>
          <li><a href="contact.html">联系</a></li>
        </ul>
      </nav>
    </div>

    <script src="{% static 'blog/js/script.js' %}"></script>
    <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
    <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
    <script>
      hljs.initHighlightingOnLoad();
      hljs.initLineNumbersOnLoad();
    </script>
  </body>
</html>

templates/blog/detail.html
{% extends './base.html' %} {% load comments_extras %} {% block main %}
<article class="post post-{{ post.pk }}">
  <header class="entry-header">
    <h1 class="entry-title">{{ post.title }}</h1>
    <div class="entry-meta">
      <span class="post-category"
        ><a href="#">{{ post.category.name }}</a></span
      >
      <span class="post-date"
        ><a href="#"
          ><time class="entry-date" datetime="{{ post.created_time }}"
            >{{ post.created_time }}</time
          ></a
        ></span
      >
      <span class="post-author"><a href="#">{{ post.author }}</a></span>
      <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
      <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
    </div>
  </header>
  <div class="entry-content clearfix">{{ post.body_html|safe }}</div>
</article>

<section class="comment-area" id="comment-area">
  <hr />
  <h3>发表评论</h3>
  {% show_comment_form post %}
  <div class="comment-list-panel">
    {% show_comments post %}
  </div>
</section>
{% endblock main %} {% block toc %} {% if post.toc %}
<div class="widget widget-content">
  <h3 class="widget-title">文章目录</h3>
  <div class="toc">
    <ul>
      {{ post.toc|safe }}
    </ul>
  </div>
</div>
{% endif %} {% endblock toc %}

templates/blog/index.html
{% extends './base.html' %} {% block main %} {% for post in post_list %}
<article class="post post-1">
  <h1 class="entry-title">
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </h1>
  <div class="entry-meta">
    <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
    <span class="post-date"
      ><a href="#"
        ><time class="entry-date" datetime="{{ post.created_time }}"
          >{{ post.created_time }}</time
        ></a
      ></span
    >
    <span class="post-author"><a href="{{ post.get_absolute_url }}">{{ post.author }}</a></span>
    <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
  </div>
  <div class="entry-content clearfix">
    <p>{{ post.excerpt|safe }}</p>
    <div class="read-more cl-effect-14">
      <a href="{{ post.get_absolute_url }}" class="more-link"
        >继续阅读 <span class="meta-nav">→</span></a
      >
    </div>
  </div>
</article>
{% empty %}
<div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}
{% if is_paginated %}
    {{ page_obj.render }}
{% endif %}
{% endblock main %}